import 'package:expandable_listview/card_page.dart';

//We create a card list consisting of  title and content.
List<Card> Cards = [
  Card("Note Title 1",
      "Content 1 Content sample Trial grade content. You can use this part like an ordinary container or a column."),
  Card("Note Title 2",
      "Note Content 2 Content sample Trial grade content. You can use this part like an ordinary container or a column."),
  Card("Note Title 3",
      "Note Content 3 Content sample Trial grade content. You can use this part like an ordinary container or a column."),
  Card("Note Title 4",
      "Note Content 4 Content sample Trial grade content. You can use this part like an ordinary container or a column."),
  Card("Note Title 5",
      "Note Content 5 Content sample Trial grade content. You can use this part like an ordinary container or a column."),
  Card("Note Title 6",
      "Note Content 6 Content sample Trial grade content. You can use this part like an ordinary container or a column."),
  Card("Note Title 7",
      "Note Content 7 Content sample Trial grade content. You can use this part like an ordinary container or a column."),
  Card("Note Title 8",
      "Note Content 8 Content sample Trial grade content. You can use this part like an ordinary container or a column."),
  Card("Note Title 9",
      "Note Content 9 Content sample Trial grade content. You can use this part like an ordinary container or a column."),
  Card("Note Title 10",
      "Note Content 10 Content sample Trial grade content. You can use this part like an ordinary container or a column."),
  Card("Note Title 11",
      "Note Content 11 Content sample Trial grade content. You can use this part like an ordinary container or a column."),
  Card("Note Title 12",
      "Note Content 12 Content sample Trial grade content. You can use this part like an ordinary container or a column."),
  Card("Note Title 13",
      "Note Content 13 Content sample Trial grade content. You can use this part like an ordinary container or a column."),
  Card("Note Title 14",
      "Note Content 14 Content sample Trial grade content. You can use this part like an ordinary container or a column."),
  Card("Note Title 15",
      "Note Content 16 Content sample Trial grade content. You can use this part like an ordinary container or a column."),
  Card("Note Title 16",
      "Note Content 17 Content sample Trial grade content. You can use this part like an ordinary container or a column."),
];